[package]
name = "raum-en-sysinfo"
version = "0.2.0"
authors = ["Raum Dellamorte <elementalsin@gmail.com>"]

[dependencies]
env_logger = "0.5"
log = "0.4"
image = "0.18"
nom = "^4.0"
time = "^0.1.37"
gl = "0.10.0"
glutin = "0.17.0"
subprocess = "0.1.13"
cupid = "*"
sysinfo = "0.5.7"
systemstat = "0.1.3"
